### PR TITLE
ENH: Allow the build, test, package workflow to be triggered

### PR DESCRIPTION
**Pull request by jhlegarreta**
Allow the build, test, package workflow to be triggered: remove the unnecessary braces around the workflow file variables.

Update the workflow file to match the latest ITK version as well as the remote modules' latest recommended versions.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@thewtex @dzenanz Any idea why the `build, test, package` Actions is not being triggered?

**Comment by jhlegarreta** [comment]
Build failures are due to `ITKVtkGlue` module being missing. Not so familiar with how this can be solved. `VTK` has also gone some mayor refactoring in its `CMake` discovery mechanism from 9.x, and I do not know if ITK has been able to accommodate to the changes. Maybe @phcerdan knows better/can suggest a solution.

**Comment by samuelgerber** [comment]
> Build failures are due to `ITKVtkGlue` module being missing. Not so familiar with how this can be solved. `VTK` has also gone some mayor refactoring in its `CMake` discovery mechanism from 9.x, and I do not know if ITK has been able to accommodate to the changes. Maybe @phcerdan knows better/can suggest a solution.

The dependency on vtkglue could be removed if the curvature filter is ported to itk.

**Comment by jhlegarreta** [comment]
> The dependency on vtkglue could be removed if the curvature filter is ported to itk.

@samuelgerber thanks for chiming in ! In the meantime, maybe we'd need to figure out how to tell our CI builds to configure and build with the `ITKVtkGlue` module. I'm not sure how easy this is/have seen other remotes facing the same issue, and I do not recall having seen a solution (e.g. such as setting the `Module_ITKVtkGlue` to `ON` in the remotes). But let me know if you find the way.

**Comment by dzenanz** [comment]
Building VtkGlue in remote CI tests should be possible. Before [build ITK](https://github.com/InsightSoftwareConsortium/ITKThinShellDemons/blob/4da5bd388b4cf923d30d647dda7db2cc617f4a10/.github/workflows/build-test-package.yml#L52-L70) step add a "build VTK step", and then add ` -DModule_ITKVtkGlue:BOOL=ON` and `-DVTK_DIR:PATH=/path/to/vtk/build` to ITK configure line.

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
This is an improvement as is, so merging.

**Pull request merged**
